# Generated by Django 6.0.5 on 2026-06-01 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('warmup', 'Warm Up'), ('interval', 'Interval'), ('recovery', 'Recovery'), ('cooldown', 'Cool Down'), ('rest', 'Rest')], max_length=20)),
                ('repeticiones', models.PositiveIntegerField(default=1)),
                ('distancia_metros', models.PositiveIntegerField(blank=True, null=True)),
                ('duracion_segundos', models.PositiveIntegerField(blank=True, null=True)),
                ('ritmo_objetivo', models.CharField(blank=True, max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workouts.workout')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
