# Generated by Django 6.0.5 on 2026-06-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_workoutstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutstep',
            name='zona',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
