# Generated by Django 6.0.5 on 2026-06-01 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_workoutstep_zona'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato', models.CharField(choices=[('tcx', 'TCX'), ('fit', 'FIT'), ('zwo', 'ZWO')], max_length=10)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(upload_to='exports/')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workout')),
            ],
        ),
    ]
